services:
  pd:
    image: pingcap/pd:v7.5.1
    container_name: pd
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - pd_data:/data
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
      - --data-dir=/data/pd
    restart: on-failure
    networks:
      - tidb_network

  tikv:
    image: pingcap/tikv:v7.5.1
    container_name: tikv
    depends_on:
      - pd
    ports:
      - "20160:20160"
    volumes:
      - tikv_data:/data
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --data-dir=/data/tikv
      - --pd=pd:2379
    restart: on-failure
    networks:
      - tidb_network

  tidb:
    image: pingcap/tidb:v7.5.1
    container_name: tidb
    depends_on:
      - tikv
      - pd
    ports:
      - "4000:4000"
      - "10080:10080"
    command:
      - --store=tikv
      - --path=pd:2379
      - --advertise-address=tidb
      - --host=0.0.0.0
    restart: on-failure
    networks:
      - tidb_network

  tiflash:
    image: pingcap/tiflash:v7.5.1
    container_name: tiflash
    depends_on:
      - pd
      - tikv
      - tidb
    ports:
      - "3930:3930"
      - "9000:9000"
      - "8123:8123"
    volumes:
      - tiflash_data:/data
    command:
      - --config=/etc/tiflash/config.toml
    environment:
      - ADDR=0.0.0.0:3930
      - ADVERTISE_ADDR=tiflash:3930
      - DATA_DIR=/data/tiflash
      - PD_ENDPOINTS=pd:2379
      - LISTEN_HOST=0.0.0.0
    restart: on-failure
    networks:
      - tidb_network


networks:
  tidb_network:
    driver: bridge

volumes:
  pd_data:
  tikv_data:
  tiflash_data:
