services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.114.0
    container_name: vm_single_node
    ports:
      - "8428:8428"  # Default port for HTTP API
    volumes:
      - vm_data:/storage  # Save data to a volume
      - ./prometheus.yml:/etc/vm/prometheus.yml  # Mount file config
    command:
      - "-storageDataPath=/storage"  # Specify the path to store data
      - "-retentionPeriod=30d"      # Retain data for 30 days
      - "-promscrape.config=/etc/vm/prometheus.yml"  # Specify the path to the config file
    restart: unless-stopped

volumes:
  vm_data: