services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: kienlt
      POSTGRES_PASSWORD: ahihi
      POSTGRES_DB: kienlt_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    driver: local