services:
  checkmk:
    image: checkmk/check-mk-free:2.1.0-latest
    container_name: checkmk
    restart: unless-stopped
    ports:
      - "8080:5000"
    volumes:
      - ./cmk_data:/omd/sites
    environment:
      - CMK_SITE=mysite
      - CMK_PASSWORD=mypassword  # Change this to a secure password

    networks:
      - checkmk-network

networks:
  checkmk-network:
    driver: bridge