# go-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app
  labels:
    app: go-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-sample-app
  template:
    metadata:
      labels:
        app: go-sample-app
    spec:
      containers:
      - name: sample-app
        image: go-sample-app:latest  # Replace with your image
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_COLLECTOR_URL
          value: "localhost:4317"  # Points to the sidecar collector
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        ports:
        - containerPort: 4317  # OTLP gRPC
        - containerPort: 4318  # OTLP HTTP
        - containerPort: 8888  # Metrics endpoint
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otelcol-contrib/config.yaml
          subPath: config.yaml
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config
---
# otel-collector-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25

    exporters:
      logging:
        loglevel: debug

      otlp:
        endpoint: "otel-collector-service:4317"
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlp]
---
# otel-collector-service.yaml - For a central collector if needed
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
spec:
  selector:
    app: otel-collector
  ports:
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
  - name: http-otlp
    port: 4318
    targetPort: 4318
---
# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: go-sample-app-service
spec:
  selector:
    app: go-sample-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP