networks:
    demo:

services:
    etcd1: &etcd
        image: kienlt992/patroni  # Updated to use your custom image
        networks: [ demo ]
        environment:
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: tutorial
            ETCD_UNSUPPORTED_ARCH: arm64
        container_name: demo-etcd1
        hostname: etcd1
        command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380

    etcd2:
        <<: *etcd
        container_name: demo-etcd2
        hostname: etcd2
        command: etcd --name etcd2 --initial-advertise-peer-urls http://etcd2:2380

    etcd3:
        <<: *etcd
        container_name: demo-etcd3
        hostname: etcd3
        command: etcd --name etcd3 --initial-advertise-peer-urls http://etcd3:2380

    haproxy:
        image: kienlt992/patroni  # Updated to use your custom image
        networks: [ demo ]
        env_file: patroni.env
        hostname: haproxy
        container_name: demo-haproxy
        ports:
            - "5000:5000" # postgres primary
            - "5001:5001" # postgres replica
            - "7000:7000" # Haproxy stats
        command: haproxy
        environment: &haproxy_env
            ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
            PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
            PATRONI_SCOPE: demo

    patroni1:
        image: kienlt992/patroni  # Updated to use your custom image
        networks: [ demo ]
        env_file: patroni.env
        hostname: patroni1
        container_name: demo-patroni1
        ports:
            - "8008:8008"  # Exposing Patroni REST API port for patroni1
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni1

    patroni2:
        image: kienlt992/patroni  # Updated to use your custom image
        networks: [ demo ]
        env_file: patroni.env
        hostname: patroni2
        container_name: demo-patroni2
        ports:
            - "8009:8008"  # Exposing Patroni REST API port for patroni2
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni2

    patroni3:
        image: kienlt992/patroni  # Updated to use your custom image
        networks: [ demo ]
        env_file: patroni.env
        hostname: patroni3
        container_name: demo-patroni3
        ports:
            - "8010:8008"  # Exposing Patroni REST API port for patroni3
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni3