services:
  jenkins:
    image: jenkins/jenkins:2.492.1-lts
    container_name: jenkins
    environment:
      # Set timezone to GMT+7 (Asia/Ho_Chi_Minh)
      - TZ=Asia/Ho_Chi_Minh
      - JAVA_OPTS=-Duser.timezone=Asia/Ho_Chi_Minh
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: