services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config", "/etc/otel/config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "55680:55680" # OpenCensus
    restart: no

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # Jaeger gRPC
      - "14268:14268" # Jaeger HTTP
      # - "4317:4317"   # OTLP gRPC
    restart: no

  # golang-app:
  #   build: .
  #   depends_on:
  #     - otel-collector
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
  #     - SERVICE_NAME=otel-go-app
