services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: kienlt
      MINIO_ROOT_PASSWORD: ahihi@wtfbro
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
    driver: local