global:
  scrape_interval: 60s
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'victoriametrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: 'node_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['node_exporter:9100']